/*
 * Project index.
 *
 * Titles, cities and years are placeholders — swap them for real projects.
 * `span` and `frame` drive the asymmetric grid; `cats` drives the filters.
 */

export type Project = {
  slug: string;
  idx: string;
  title: string;
  meta: string;
  cats: string[];
  src: string;
  alt: string;
  span: number;
  frame: string;
  offset?: boolean;
};

export const FILTERS = [
  { key: 'all', label: 'All' },
  { key: 'residential', label: 'Residential' },
  { key: 'commercial', label: 'Commercial' },
  { key: 'interior', label: 'Interior' },
  { key: 'walkthrough', label: 'Walkthrough' },
  { key: 'vr360', label: '360 & VR' },
  { key: 'floorplan', label: 'Floor plans' },
  { key: 'scale-model', label: 'Scale models' },
];

export const projects: Project[] = [
  {
    slug: 'axis-business-district',
    idx: '001',
    title: 'Axis Business District',
    meta: 'Commercial · Bengaluru · 2025',
    cats: ['commercial', 'walkthrough'],
    src: '/assets/img/work/com-01.webp',
    alt: 'Dusk render of a mixed-use business district',
    span: 7,
    frame: 'frame--3x2',
  },
  {
    slug: 'meridian-heights',
    idx: '002',
    title: 'Meridian Heights',
    meta: 'Residential · Mumbai · 2025',
    cats: ['residential'],
    src: '/assets/img/work/res-03.webp',
    alt: 'Twilight render of a slender residential tower',
    span: 5,
    frame: 'frame--3x4',
    offset: true,
  },
  {
    slug: 'the-palm-courtyard',
    idx: '003',
    title: 'The Palm Courtyard',
    meta: 'Interior · Hyderabad · 2025',
    cats: ['interior'],
    src: '/assets/img/work/int-01.webp',
    alt: 'Interior visualisation of a residential living room',
    span: 4,
    frame: 'frame--4x3',
  },
  {
    slug: 'northgate-masterplan',
    idx: '004',
    title: 'Northgate Masterplan',
    meta: 'Scale model · Dubai · 2024',
    cats: ['scale-model'],
    src: '/assets/img/work/sm-02.webp',
    alt: 'Physical scale model with integrated lighting',
    span: 4,
    frame: 'frame--4x3',
  },
  {
    slug: 'aurum-residences',
    idx: '005',
    title: 'Aurum Residences',
    meta: 'Township · Bengaluru · 2024',
    cats: ['residential'],
    src: '/assets/img/work/res-07.webp',
    alt: 'Aerial render of a residential township',
    span: 4,
    frame: 'frame--4x3',
  },
  {
    slug: 'northpoint-exchange',
    idx: '006',
    title: 'Northpoint Exchange',
    meta: 'Commercial · Delhi · 2024',
    cats: ['commercial'],
    src: '/assets/img/work/com-03.webp',
    alt: 'Commercial tower render at dusk',
    span: 5,
    frame: 'frame--4x3',
  },
  {
    slug: 'silverline-gardens',
    idx: '007',
    title: 'Silverline Gardens',
    meta: 'Residential · Bengaluru · 2024',
    cats: ['residential', 'walkthrough'],
    src: '/assets/img/work/res-06.webp',
    alt: 'Landscaped podium of a residential development',
    span: 7,
    frame: 'frame--3x2',
  },
  {
    slug: 'casa-lumiere',
    idx: '008',
    title: 'Casa Lumière',
    meta: 'Interior · Mumbai · 2024',
    cats: ['interior'],
    src: '/assets/img/work/int-04.webp',
    alt: 'Interior render of a furnished apartment',
    span: 4,
    frame: 'frame--4x3',
  },
  {
    slug: 'horizon-vr-suite',
    idx: '009',
    title: 'Horizon VR Suite',
    meta: '360 & VR · Dubai · 2024',
    cats: ['vr360'],
    src: '/assets/img/work/vr-01.webp',
    alt: '360 degree panoramic visualisation',
    span: 4,
    frame: 'frame--4x3',
  },
  {
    slug: 'unit-type-library',
    idx: '010',
    title: 'Unit Type Library',
    meta: 'Floor plans · Hyderabad · 2024',
    cats: ['floorplan'],
    src: '/assets/img/work/fp-01.webp',
    alt: '3D floor plan with furniture layout',
    span: 4,
    frame: 'frame--4x3',
  },
  {
    slug: 'vantage-corporate-park',
    idx: '011',
    title: 'Vantage Corporate Park',
    meta: 'Commercial · Hyderabad · 2023',
    cats: ['commercial'],
    src: '/assets/img/work/com-05.webp',
    alt: 'Commercial campus render',
    span: 6,
    frame: 'frame--3x2',
  },
  {
    slug: 'elmwood-enclave',
    idx: '012',
    title: 'Elmwood Enclave',
    meta: 'Residential · Delhi · 2023',
    cats: ['residential'],
    src: '/assets/img/work/res-05.webp',
    alt: 'Residential exterior render',
    span: 6,
    frame: 'frame--3x2',
  },
  {
    slug: 'crescent-bay-model',
    idx: '013',
    title: 'Crescent Bay Model',
    meta: 'Scale model · Mumbai · 2023',
    cats: ['scale-model'],
    src: '/assets/img/work/sm-04.webp',
    alt: 'Detail of an illuminated architectural scale model',
    span: 4,
    frame: 'frame--4x3',
  },
  {
    slug: 'sable-show-flat',
    idx: '014',
    title: 'Sable Show Flat',
    meta: 'Interior · Bengaluru · 2023',
    cats: ['interior'],
    src: '/assets/img/work/int-06.webp',
    alt: 'Bedroom interior visualisation',
    span: 4,
    frame: 'frame--4x3',
  },
  {
    slug: 'the-arcade',
    idx: '015',
    title: 'The Arcade',
    meta: 'Retail · Bengaluru · 2023',
    cats: ['commercial'],
    src: '/assets/img/work/com-08.webp',
    alt: 'Retail frontage architectural render',
    span: 4,
    frame: 'frame--4x3',
  },
  {
    slug: 'verdant-spire',
    idx: '016',
    title: 'Verdant Spire',
    meta: 'Residential · Mumbai · 2023',
    cats: ['residential'],
    src: '/assets/img/work/res-04.webp',
    alt: 'Tall residential tower render',
    span: 5,
    frame: 'frame--3x4',
  },
  {
    slug: 'quay-mixed-use',
    idx: '017',
    title: 'Quay Mixed-Use',
    meta: 'Mixed use · Dubai · 2023',
    cats: ['commercial', 'walkthrough'],
    src: '/assets/img/work/com-07.webp',
    alt: 'Mixed-use development render',
    span: 7,
    frame: 'frame--3x2',
    offset: true,
  },
  {
    slug: 'skyline-immersive',
    idx: '018',
    title: 'Skyline Immersive',
    meta: '360 & VR · Bengaluru · 2023',
    cats: ['vr360'],
    src: '/assets/img/work/vr-02.webp',
    alt: 'Virtual reality tour still',
    span: 4,
    frame: 'frame--4x3',
  },
  {
    slug: 'tower-b-plan-set',
    idx: '019',
    title: 'Tower B Plan Set',
    meta: 'Floor plans · Delhi · 2023',
    cats: ['floorplan'],
    src: '/assets/img/work/fp-02.webp',
    alt: 'Isometric 3D floor plan',
    span: 4,
    frame: 'frame--4x3',
  },
  {
    slug: 'atrium-clubhouse',
    idx: '020',
    title: 'Atrium Clubhouse',
    meta: 'Interior · Hyderabad · 2022',
    cats: ['interior'],
    src: '/assets/img/work/int-03.webp',
    alt: 'Dining area interior render',
    span: 4,
    frame: 'frame--4x3',
  },
  {
    slug: 'willowbrook-phase-ii',
    idx: '021',
    title: 'Willowbrook Phase II',
    meta: 'Residential · Bengaluru · 2022',
    cats: ['residential'],
    src: '/assets/img/work/res-08.webp',
    alt: 'Residential development exterior',
    span: 6,
    frame: 'frame--3x2',
  },
  {
    slug: 'harbourfront-model',
    idx: '022',
    title: 'Harbourfront Model',
    meta: 'Scale model · Dubai · 2022',
    cats: ['scale-model'],
    src: '/assets/img/work/sm-05.webp',
    alt: 'Masterplan scale model on display',
    span: 6,
    frame: 'frame--3x2',
  },
  {
    slug: 'ironside-offices',
    idx: '023',
    title: 'Ironside Offices',
    meta: 'Commercial · Mumbai · 2022',
    cats: ['commercial'],
    src: '/assets/img/work/com-06.webp',
    alt: 'Office lobby exterior render',
    span: 4,
    frame: 'frame--4x3',
  },
  {
    slug: 'amber-court',
    idx: '024',
    title: 'Amber Court',
    meta: 'Residential · Hyderabad · 2022',
    cats: ['residential'],
    src: '/assets/img/work/res-10.webp',
    alt: 'Residential podium and amenity deck render',
    span: 4,
    frame: 'frame--4x3',
  },
  {
    slug: 'loft-360-tour',
    idx: '025',
    title: 'Loft 360 Tour',
    meta: '360 & VR · Delhi · 2022',
    cats: ['vr360', 'floorplan'],
    src: '/assets/img/work/vr-03.webp',
    alt: 'Panoramic interior tour still',
    span: 4,
    frame: 'frame--4x3',
  },
];

export const featured = projects.slice(0, 5);
